---
title: "Teste08"
author: "Guilherme Pazian"
date: "31 de maio de 2017"
output: pdf_document
---

modelo

wage - Ganho médio por hora da esposa em dólares em 1975.
educ - Formaçăo educacional da esposa, em anos.
siblings - Número de irmăos da esposa.


wage(salario) ~ educ(mulher) + siblings (irmăos) "instrumento"

\begin{center}

Modelo 9: MQ2E, usando as observaĂ§Ăľes 1--428\\
VariĂĄvel dependente: l\_wage\\
Instrumentado: educ \\
Instrumentos: const siblings fathereduc mothereduc exper hours kidsl6 \\
largecity \\
Erros padrĂŁo robustos Ă  heteroscedasticidade, variante HC1

\vspace{1em}

\begin{tabular}{lr@{,}lr@{,}lr@{,}lr@{,}l}
  &
 \multicolumn{2}{c}{Coeficiente} &
  \multicolumn{2}{c}{Erro\ PadrĂŁo} &
   \multicolumn{2}{c}{razĂŁo-$t$} &
    \multicolumn{2}{c}{p-valor} \\[1ex]
const &
  0&255083 &
    0&440924 &
      0&5785 &
        0&5632 \\
educ &
  0&0581777 &
    0&0345822 &
      1&682 &
        0&0932 \\
exper &
  0&0167067 &
    0&00437971 &
      3&815 &
        0&0002 \\
hours &
  $-$5&78318\textrm{e--005} &
    6&66148\textrm{e--005} &
      $-$0&8682 &
        0&3858 \\
kidsl6 &
  $-$0&0344118 &
    0&103694 &
      $-$0&3319 &
        0&7402 \\
largecity &
  0&0952688 &
    0&0684986 &
      1&391 &
        0&1650 \\
\end{tabular}

\vspace{1ex}
\begin{tabular}{lrlr}
MĂŠdia var. dependente &  1,190173 & D.P. var. dependente &  0,723198 \\
Soma resĂ?d. quadrados &  194,3264 & E.P. da regressĂŁo &  0,678594 \\
$R^2$ &  0,140161 & $R^2$ ajustado &  0,129973 \\
$F(5, 422)$ &  4,557122 & P-valor($F$) &  0,000465 \\
\end{tabular}

\vspace{1em}
\begin{raggedright}
Teste de Hausman --\\
\quad HipĂłtese nula: as estimativas por MQO săo consistentes\\
\quad Estatística de teste assintótica: $\chi^2(1)$ = 3,02292\\
\quad com p-valor = 0,0820958\\
\vspace{1ex}
Teste de Sargan para a sobre-identificaĂ§ĂŁo --\\
\quad HipĂłtese nula: todos os instrumentos săo válidos\\
\quad Estatística de teste: LM = 0,584092\\
\quad com p-valor = $P$($\chi^2(2) >$ 0,584092) = 0,746734\\
\vspace{1ex}
Teste de instrumento fraco -- \\
\quad First-stage $F(3, 420)$ = 30,4599 \\
\end{raggedright}

\end{center}


\newpage

\begin{center}

Modelo 10: MQ2E, usando as observaĂ§Ăľes 1--428\\
VariĂĄvel dependente: l\_wage\\
Instrumentado: educ \\
Instrumentos: const siblings fathereduc mothereduc exper \\
Erros padrĂŁo robustos Ă  heteroscedasticidade, variante HC1

\vspace{1em}

\begin{tabular}{lr@{,}lr@{,}lr@{,}lr@{,}l}
  &
 \multicolumn{2}{c}{Coeficiente} &
  \multicolumn{2}{c}{Erro\ PadrĂŁo} &
   \multicolumn{2}{c}{razĂŁo-$t$} &
    \multicolumn{2}{c}{p-valor} \\[1ex]
const &
  0&171469 &
    0&423132 &
      0&4052 &
        0&6855 \\
educ &
  0&0645310 &
    0&0330625 &
      1&952 &
        0&0516 \\
exper &
  0&0154796 &
    0&00414108 &
      3&738 &
        0&0002 \\
\end{tabular}

\vspace{1ex}
\begin{tabular}{lrlr}
MĂŠdia var. dependente &  1,190173 & D.P. var. dependente &  0,723198 \\
Soma resĂ?d. quadrados &  194,7016 & E.P. da regressĂŁo &  0,676847 \\
$R^2$ &  0,140122 & $R^2$ ajustado &  0,136075 \\
$F(2, 425)$ &  8,586489 & P-valor($F$) &  0,000221 \\
\end{tabular}

\vspace{1em}
\begin{raggedright}
Teste de Hausman --\\
\quad HipĂłtese nula: as estimativas por MQO săo consistentes\\
\quad Estatística de teste assintótica: $\chi^2(1)$ = 2,74038\\
\quad com p-valor = 0,0978414\\
\vspace{1ex}
Teste de Sargan para a sobre-identificaĂ§ĂŁo --\\
\quad HipĂłtese nula: todos os instrumentos săo válidos\\
\quad Estatística de teste: LM = 0,828443\\
\quad com p-valor = $P$($\chi^2(2) >$ 0,828443) = 0,660854\\
\vspace{1ex}
Teste de instrumento fraco -- \\
\quad First-stage $F(3, 423)$ = 33,8202 \\
\end{raggedright}

\end{center}



